[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "https://alertzy.app/send"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"