[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Disable CRA's eslint-webpack-plugin during Netlify builds to avoid
  # "Cannot set properties of undefined (setting 'defaultMeta')" crashes
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/api/alertzy/*"
  to = "/.netlify/functions/alertzy"
  status = 200

[[headers]]
  for = "/.netlify/functions/alertzy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "content-type"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
