const purgecss = require('@fullhuman/postcss-purgecss').default;
const autoprefixer = require('autoprefixer');

const isProd = process.env.NODE_ENV === 'production';

module.exports = {
  plugins: [
    isProd && purgecss({
      content: [
        './index.html',
        './src/**/*.{js,jsx,ts,tsx}',
      ],
      defaultExtractor: (content) => content.match(/[^<>'"`\s\.\:]+/g) || [],
      keyframes: false, // keep all keyframes to avoid prod-only animation breakage
      variables: true,
      safelist: [
        // Global tokens and small utility classes
        'accent', 'purple',
        // Animation/status classes used dynamically
        /^tx-/, /^fps-meter/,
        // App layout + animation entrance
        /^App/, /^anime-layout/, /^anime-section/,
        // Feature scopes
        /^hero-/, /^lore-/, /^skill-/, /^project-/, /^quest-/, /^resume-/, /^section-nav/, /^preloader/,
        // Bootstrap grid/utilities (kept in prod; generated by react-bootstrap at runtime)
        /^container/, /^row$/, /^col/, /^g[xy]?-/,
        /^offset-/, /^order-/,
        /^d-/, /^flex/, /^justify-/, /^align-/,
        /^text-/, /^fw-/, /^lh-/,
        /^m[trblxy]?-/, /^p[trblxy]?-/,
        /^btn/, /^badge/, /^shadow/,
        /^position-/, /^top-/, /^bottom-/, /^start-/, /^end-/, /^z-/,
        /^modal/, /^fade$/, /^show$/, /^collapse/, /^navbar/, /^nav/, /^dropdown/, /^card/, /^alert/, /^list-group/,
        // react-pdf text/annotation layers
        /^react-pdf__/,
        /^textLayer$/, /^annotationLayer$/,
      ],
    }),
    autoprefixer(),
  ].filter(Boolean),
};
